// @generated by AngelscriptTestCode/CodeGenTool format=v2
// source=Language/Counter.as length=420 sha256=28d6fc3cba07a13cf12c6ced5146377bf7d85bcbef71ff1a55d9fb0762f465d9
#include "Framework/Catalog/AngelscriptTestCodeRegistration.h"
#include "Framework/Source/AngelscriptTestCodeBuilder.h"
#include "Framework/Source/AngelscriptTestSource.h"
#include "Framework/Source/AngelscriptTestSourceDescriptor.h"

#if WITH_ANGELSCRIPT_TESTS

namespace AngelscriptTest::Generated
{
static FAngelscriptTestCodeRegistration GRegistration_Language_Counter(
	{
		.Version = TEXT("v1"),
		.Tag = TEXT("Language/Counter"),
		.Summary = TEXT("Counter source variants."),
		.Topics = {TEXT("Language"), TEXT("Reload")}
	},
	+[](const FAngelscriptTestFileMeta& FileMeta)
	{
		FAngelscriptTestCodeBuilder Builder(FileMeta);
		Builder.AddRoot(
			{
				.Tag = TEXT("root"),
				.Summary = TEXT("Define the initial counter."),
				.Topics = {TEXT("Baseline")}
			},
			AS_TEST_SOURCE(R"AS(
			class Counter
			{
			    int Value = 0;
			}

			)AS"),
			FAngelscriptTestSourceDescriptor{
				.AuthoredPath = TEXT("Language/Counter.as"),
				.AuthoredLine = 12,
				.AuthoredEnd = 217,
				.OriginSpans = {
					{.CleanBegin = 0, .AuthoredBegin = 180, .Length = 37},
				}
			}
		);
		Builder.AddVersion(
			{
				.Tag = TEXT("add-step"),
				.Parent = TEXT("root"),
				.Summary = TEXT("Add a configurable counter step."),
				.Topics = {TEXT("Fields"), TEXT("Reload")}
			},
			AS_TEST_SOURCE(R"AS(
			class Counter
			{
			    int Value = 0;
			    int Step = 1;
			}

			)AS"),
			FAngelscriptTestSourceDescriptor{
				.AuthoredPath = TEXT("Language/Counter.as"),
				.AuthoredLine = 24,
				.AuthoredEnd = 408,
				.OriginSpans = {
					{.CleanBegin = 0, .AuthoredBegin = 353, .Length = 55},
				}
			}
		);
		return Builder.Build();
	},
	UE_MODULE_NAME,
	"AngelscriptTestCode/Language/Counter.as",
	1);
}

#endif // WITH_ANGELSCRIPT_TESTS
