"""Pure raw-byte to C++ projection rendering."""

from __future__ import annotations

from .model import SourceInput


GENERATOR_SIGNATURE = "// @generated by AngelscriptTestCode/CodeGenTool format=v1"


def _escape_cpp_text(value: str) -> str:
    escaped: list[str] = []
    for character in value:
        codepoint = ord(character)
        if character == "\\":
            escaped.append("\\\\")
        elif character == '"':
            escaped.append('\\"')
        elif 0x20 <= codepoint <= 0x7E:
            escaped.append(character)
        elif codepoint <= 0xFFFF:
            escaped.append(f"\\u{codepoint:04x}")
        else:
            escaped.append(f"\\U{codepoint:08x}")
    return "".join(escaped)


def _format_byte_rows(content: bytes) -> list[str]:
    payload = content if content else b"\x00"
    return [
        "\t" + ", ".join(f"0x{byte:02x}" for byte in payload[index : index + 12]) + ","
        for index in range(0, len(payload), 12)
    ]


def render_projection(source: SourceInput) -> bytes:
    suffix = source.symbol_suffix
    file_tag = _escape_cpp_text(source.file_tag)
    source_path = _escape_cpp_text(source.relative_path)
    rows = _format_byte_rows(source.content)
    lines = [
        GENERATOR_SIGNATURE,
        (
            f"// source={source.relative_path} length={len(source.content)} "
            f"sha256={source.content_sha256}"
        ),
        '#include "Containers/ArrayView.h"',
        '#include "NewVersion/Framework/Catalog/AngelscriptTestCodeRegistration.h"',
        '#include "NewVersion/Framework/Source/AngelscriptTestSourceParser.h"',
        "",
        "#if WITH_ANGELSCRIPT_TESTS",
        "",
        "namespace AngelscriptTest::Generated",
        "{",
        "namespace",
        "{",
        f"constexpr uint8 GSource_{suffix}[] =",
        "{",
        *rows,
        "};",
        f"constexpr int32 GSourceLength_{suffix} = {len(source.content)};",
        "",
        f"FAngelscriptTestCodeRegistration GRegistration_{suffix}(",
        "\t{",
        '\t\t.Version = TEXT("v1"),',
        f'\t\t.Tag = TEXT("{file_tag}"),',
        f'\t\t.Summary = TEXT("Generated from AngelscriptTestCode/{source_path}."),',
        "\t},",
        "\t+[](const FAngelscriptTestFileMeta& FileMeta)",
        "\t{",
        "\t\treturn FAngelscriptTestSourceParser::Parse(",
        "\t\t\tFileMeta.Tag,",
        f"\t\t\tMakeArrayView(GSource_{suffix}, GSourceLength_{suffix}));",
        "\t},",
        "\tUE_MODULE_NAME,",
        f'\t"AngelscriptTestCode/{source_path}",',
        "\t1);",
        "}",
        "}",
        "",
        "#endif // WITH_ANGELSCRIPT_TESTS",
        "",
    ]
    return "\n".join(lines).encode("utf-8")
