"""Pure ParsedFile to structured C++ projection rendering."""

from __future__ import annotations

from .model import CodegenError, ParsedFile, ParsedVersion


GENERATOR_SIGNATURE = "// @generated by AngelscriptTestCode/CodeGenTool format=v2"
_LITERAL_INDENT = b"\t\t\t"


def encode_file_tag(file_tag: str) -> str:
    encoded: list[str] = []
    for character in file_tag:
        if character == "/":
            encoded.append("_")
        elif character.isalnum() or character == "_":
            encoded.append(character)
        else:
            encoded.append(f"_u{ord(character):04x}")
    return "".join(encoded) or "_"


def plan_registration_symbols(file_tags: tuple[str, ...]) -> dict[str, str]:
    planned: dict[str, str] = {}
    seen: dict[str, str] = {}
    for file_tag in file_tags:
        symbol = encode_file_tag(file_tag)
        previous = seen.get(symbol)
        if previous is not None and previous != file_tag:
            raise CodegenError(
                "Generated registration symbols collide: "
                f"{previous!r} and {file_tag!r} both encode to {symbol!r}"
            )
        seen[symbol] = file_tag
        planned[file_tag] = symbol
    return planned


def _escape_cpp_text(value: str) -> str:
    escaped: list[str] = []
    for character in value:
        codepoint = ord(character)
        if character == "\\":
            escaped.append("\\\\")
        elif character == '"':
            escaped.append('\\"')
        elif 0x20 <= codepoint <= 0x7E:
            escaped.append(character)
        elif codepoint <= 0xFFFF:
            escaped.append(f"\\u{codepoint:04x}")
        else:
            escaped.append(f"\\U{codepoint:08x}")
    return "".join(escaped)


def _text(value: str) -> str:
    return f'TEXT("{_escape_cpp_text(value)}")'


def _choose_delimiter(clean: bytes) -> str:
    index = 0
    while True:
        delimiter = "AS" if index == 0 else f"AS{index}"
        closer = f"){delimiter}\"".encode("ascii")
        if closer not in clean:
            return delimiter
        index += 1


def wrap_as_test_source(clean: bytes) -> str:
    delimiter = _choose_delimiter(clean)
    body = bytearray(b"\n")
    if clean:
        started = False
        for byte in clean:
            if not started:
                body.extend(_LITERAL_INDENT)
                started = True
            body.append(byte)
            if byte == 0x0A:
                started = False
        if not clean.endswith(b"\n"):
            body.append(0x0A)
        else:
            body.append(0x0A)
    body.extend(_LITERAL_INDENT)
    literal = body.decode("utf-8")
    return f'AS_TEST_SOURCE(R"{delimiter}({literal}){delimiter}")'


def _topics_literal(topics: tuple[str, ...]) -> str | None:
    if not topics:
        return None
    joined = ", ".join(_text(topic) for topic in topics)
    return f".Topics = {{{joined}}}"


def _version_meta_lines(version: ParsedVersion, indent: str) -> list[str]:
    lines = [
        f"{indent}{{",
        f"{indent}\t.Tag = {_text(version.tag)},",
    ]
    if version.parent is not None:
        lines.append(f"{indent}\t.Parent = {_text(version.parent)},")
    lines.append(f"{indent}\t.Summary = {_text(version.summary)},")
    topics = _topics_literal(version.topics)
    if topics is not None:
        lines.append(f"{indent}\t{topics},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append(f"{indent}}}")
    return lines


def _descriptor_lines(parsed: ParsedFile, version: ParsedVersion, indent: str) -> list[str]:
    lines = [
        f"{indent}FAngelscriptTestSourceDescriptor{{",
        f"{indent}\t.AuthoredPath = {_text(parsed.source.relative_path)},",
        f"{indent}\t.AuthoredLine = {version.authored_body_line},",
        f"{indent}\t.AuthoredEnd = {version.authored_end},",
    ]
    annotations = version.annotations
    if annotations.points or annotations.breakpoints or annotations.ranges:
        lines.append(f"{indent}\t.Annotations = {{")
        if annotations.points:
            lines.append(f"{indent}\t\t.Points = {{")
            for point in annotations.points:
                lines.append(
                    f"{indent}\t\t\t{{.Name = {_text(point.name)}, .Offset = {point.offset}}},"
                )
            lines.append(f"{indent}\t\t}},")
        if annotations.breakpoints:
            lines.append(f"{indent}\t\t.Breakpoints = {{")
            for breakpoint in annotations.breakpoints:
                lines.append(
                    f"{indent}\t\t\t{{.Name = {_text(breakpoint.name)}, .Offset = {breakpoint.offset}}},"
                )
            lines.append(f"{indent}\t\t}},")
        if annotations.ranges:
            lines.append(f"{indent}\t\t.Ranges = {{")
            for range_item in annotations.ranges:
                lines.append(
                    f"{indent}\t\t\t{{.Name = {_text(range_item.name)}, "
                    f".Begin = {range_item.begin}, .End = {range_item.end}}},"
                )
            lines.append(f"{indent}\t\t}},")
        lines.append(f"{indent}\t}},")
    if version.origin_spans:
        lines.append(f"{indent}\t.OriginSpans = {{")
        for span in version.origin_spans:
            lines.append(
                f"{indent}\t\t{{.CleanBegin = {span.clean_begin}, "
                f".AuthoredBegin = {span.authored_begin}, .Length = {span.length}}},"
            )
        lines.append(f"{indent}\t}}")
    lines.append(f"{indent}}}")
    return lines


def _add_call_lines(parsed: ParsedFile, version: ParsedVersion) -> list[str]:
    method = "AddRoot" if version.tag == "root" else "AddVersion"
    source_literal = wrap_as_test_source(version.clean_source)
    lines = [
        f"\t\tBuilder.{method}(",
        *_version_meta_lines(version, "\t\t\t"),
    ]
    lines[-1] += ","
    lines.append(f"\t\t\t{source_literal},")
    lines.extend(_descriptor_lines(parsed, version, "\t\t\t"))
    lines.append("\t\t);")
    return lines


def render_projection(parsed: ParsedFile) -> bytes:
    source = parsed.source
    symbol = plan_registration_symbols((source.file_tag,))[source.file_tag]
    topics = _topics_literal(parsed.topics)
    file_meta = [
        "\t{",
        f'\t\t.Version = {_text(parsed.format_version)},',
        f"\t\t.Tag = {_text(source.file_tag)},",
        f"\t\t.Summary = {_text(parsed.summary)},",
    ]
    if topics is not None:
        file_meta.append(f"\t\t{topics}")
    file_meta.append("\t},")

    factory: list[str] = [
        "\t+[](const FAngelscriptTestFileMeta& FileMeta)",
        "\t{",
        "\t\tFAngelscriptTestCodeBuilder Builder(FileMeta);",
    ]
    for version in parsed.versions:
        factory.extend(_add_call_lines(parsed, version))
    factory.extend(
        [
            "\t\treturn Builder.Build();",
            "\t},",
        ]
    )

    lines = [
        GENERATOR_SIGNATURE,
        (
            f"// source={source.relative_path} length={len(source.content)} "
            f"sha256={source.content_sha256}"
        ),
        '#include "Framework/Catalog/AngelscriptTestCodeRegistration.h"',
        '#include "Framework/Source/AngelscriptTestCodeBuilder.h"',
        '#include "Framework/Source/AngelscriptTestSource.h"',
        '#include "Framework/Source/AngelscriptTestSourceDescriptor.h"',
        "",
        "#if WITH_ANGELSCRIPT_TESTS",
        "",
        "namespace AngelscriptTest::Generated",
        "{",
        f"static FAngelscriptTestCodeRegistration GRegistration_{symbol}(",
        *file_meta,
        *factory,
        "\tUE_MODULE_NAME,",
        f'\t"AngelscriptTestCode/{_escape_cpp_text(source.relative_path)}",',
        "\t1);",
        "}",
        "",
        "#endif // WITH_ANGELSCRIPT_TESTS",
        "",
    ]
    return "\n".join(lines).encode("utf-8")
