from __future__ import annotations

import sys
import tempfile
import time
import unittest
from pathlib import Path

TOOL_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOL_ROOT))

from angelscript_test_codegen.cpp_renderer import GENERATOR_SIGNATURE
from angelscript_test_codegen.model import CodegenError
from angelscript_test_codegen.sync import apply_sync_plan, build_sync_plan

LEGACY_GENERATOR_SIGNATURE = "// @generated by AngelscriptTestCode/CodeGenTool format=v1"


def valid_fixture(summary: str, body: bytes = b"class A {}\n") -> bytes:
    return (
        b"/**\n"
        b" * @version v1\n"
        + f" * @summary {summary}\n".encode("ascii")
        + b" */\n"
        b"/**\n"
        b" * @version root\n"
        b" * @summary Root body.\n"
        b" */\n"
        + body
        + b"/** @end */\n"
    )


INVALID_FIXTURE = (
    b"/**\n"
    b" * @version v1\n"
    b" * @summary File header is valid.\n"
    b" */\n"
    b"/**\n"
    b" * @version root\n"
    b" * @summary\n"
    b" */\n"
    b"class Broken {}\n"
    b"/** @end */\n"
)

SIGNED_V1 = (
    f"{LEGACY_GENERATOR_SIGNATURE}\n"
    "constexpr uint8 GSource[] = {0x2f};\n"
    "return FAngelscriptTestSourceParser::Parse(FileMeta.Tag, MakeArrayView(GSource, 1));\n"
).encode("utf-8")


class SyncTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        root = Path(self.temporary_directory.name)
        self.author_root = root / "Author"
        self.generated_root = root / "Generated"
        self.author_root.mkdir()

    def tearDown(self) -> None:
        self.temporary_directory.cleanup()

    def write_source(self, relative_path: str, content: bytes) -> None:
        path = self.author_root / Path(relative_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)

    def test_protocol_failure_leaves_all_projections_untouched(self) -> None:
        self.write_source("A.as", valid_fixture("First valid fixture."))
        self.write_source("B.as", valid_fixture("Second valid fixture."))
        self.write_source("Broken.as", INVALID_FIXTURE)
        self.generated_root.mkdir()
        existing = self.generated_root / "A.generated.cpp"
        existing.write_bytes((GENERATOR_SIGNATURE + "\nexisting\n").encode("utf-8"))
        before_bytes = existing.read_bytes()
        before_mtime = existing.stat().st_mtime_ns

        with self.assertRaises(CodegenError) as raised:
            build_sync_plan(self.author_root, self.generated_root)

        codes = [diagnostic.code for diagnostic in raised.exception.diagnostics]
        paths = [diagnostic.source_path for diagnostic in raised.exception.diagnostics]
        self.assertIn("EmptyVersionSummary", codes)
        self.assertIn("Broken.as", paths)
        self.assertIn("Broken.as", str(raised.exception))
        self.assertEqual(before_bytes, existing.read_bytes())
        self.assertEqual(before_mtime, existing.stat().st_mtime_ns)
        self.assertFalse((self.generated_root / "B.generated.cpp").exists())

    def test_signed_v1_becomes_expected_v2(self) -> None:
        self.write_source("A.as", valid_fixture("Replace signed v1."))
        self.generated_root.mkdir()
        output = self.generated_root / "A.generated.cpp"
        output.write_bytes(SIGNED_V1)

        plan = build_sync_plan(self.author_root, self.generated_root)
        self.assertEqual(("A.generated.cpp",), plan.changed)
        self.assertEqual((), plan.missing)
        self.assertEqual((), plan.stale)

        apply_sync_plan(plan)
        replacement = output.read_bytes()
        text = replacement.decode("utf-8")
        self.assertTrue(replacement.startswith((GENERATOR_SIGNATURE + "\n").encode("utf-8")))
        self.assertIn("FAngelscriptTestSourceDescriptor", text)
        self.assertNotIn("constexpr uint8 GSource", text)
        self.assertNotIn("FAngelscriptTestSourceParser", text)

    def test_renamed_signed_v1_is_stale_owned(self) -> None:
        self.write_source("A.as", valid_fixture("Keep current path."))
        self.generated_root.mkdir()
        stale = self.generated_root / "Old.generated.cpp"
        stale.write_bytes(SIGNED_V1)

        plan = build_sync_plan(self.author_root, self.generated_root)
        self.assertEqual(("A.generated.cpp",), plan.missing)
        self.assertEqual(("Old.generated.cpp",), plan.stale)

        apply_sync_plan(plan)
        self.assertTrue((self.generated_root / "A.generated.cpp").is_file())
        self.assertFalse(stale.exists())
        self.assertTrue(build_sync_plan(self.author_root, self.generated_root).is_clean)

    def test_unsigned_and_unrelated_extras_are_preserved(self) -> None:
        self.write_source("A.as", valid_fixture("Desired fixture."))
        self.generated_root.mkdir()
        manual = self.generated_root / "Manual.generated.cpp"
        keep = self.generated_root / "Keep.txt"
        manual.write_text("handwritten\n", encoding="utf-8")
        keep.write_text("keep\n", encoding="utf-8")

        plan = build_sync_plan(self.author_root, self.generated_root)
        self.assertEqual(("Keep.txt", "Manual.generated.cpp"), plan.unsafe_extra)
        apply_sync_plan(plan)

        self.assertTrue((self.generated_root / "A.generated.cpp").is_file())
        self.assertEqual("handwritten\n", manual.read_text(encoding="utf-8"))
        self.assertEqual("keep\n", keep.read_text(encoding="utf-8"))
        self.assertEqual(
            ("Keep.txt", "Manual.generated.cpp"),
            build_sync_plan(self.author_root, self.generated_root).unsafe_extra,
        )

    def test_noop_keeps_timestamps(self) -> None:
        self.write_source("A.as", valid_fixture("No-op fixture."))
        apply_sync_plan(build_sync_plan(self.author_root, self.generated_root))
        output = self.generated_root / "A.generated.cpp"
        self.assertTrue(output.is_file())
        self.assertTrue(build_sync_plan(self.author_root, self.generated_root).is_clean)

        first_mtime = output.stat().st_mtime_ns
        time.sleep(0.02)
        apply_sync_plan(build_sync_plan(self.author_root, self.generated_root))
        self.assertEqual(first_mtime, output.stat().st_mtime_ns)

    def test_invalid_inputs_do_not_mutate_existing_projection(self) -> None:
        self.generated_root.mkdir()
        existing = self.generated_root / "Existing.generated.cpp"
        existing.write_bytes((GENERATOR_SIGNATURE + "\nexisting\n").encode("utf-8"))
        before_bytes = existing.read_bytes()
        before_mtime = existing.stat().st_mtime_ns

        from angelscript_test_codegen.discovery import _validate_unique_paths

        with self.assertRaises(CodegenError):
            _validate_unique_paths(["Folder/Case.as", "folder/case.as"])

        self.assertEqual(before_bytes, existing.read_bytes())
        self.assertEqual(before_mtime, existing.stat().st_mtime_ns)


if __name__ == "__main__":
    unittest.main()
